#
# This is a template - not used at runtime
#
repos:
  # format: repo_url [ - internal_directory_where_the_dependency_tree_command_is_executed ]
  - https://github.com/org/repo-1
  - https://github.com/org/repo-2
  - https://github.com/org/repo-3 - repo/internal/dir

# local directory where the repositories are cloned
workDirectory: /home/user/tmp/dep-viz

gitConfig:
  # full path to the git executable
  executable: /usr/bin/git
  # used by git cloning; in combination with the auth token must have access to all repositories above
  username: valid-username-here
  # used by git cloning; in combination with the username must have access to all repositories above
  token: valid-token-here

mavenConfig:
  # full path to the mvn executable
  executable: /usr/bin/mvn
  goal: dependency:tree
  scope: compile
  # root(s) of dependency sub-trees to be considered for processing; comma separated, maven glob format
  includes: com.target.package.*::jar,org.target.package.*::jar

graphvizConfig:
  # full path to the dot executable, part of https://www.graphviz.org/ visualization suite
  executable: /usr/bin/dot
  # output format - most vector and bitmap image formats are supported
  format: svg
  # output file
  output: dep-graph.svg

features:
  # set to 'true' if you want to skip rendering of single version, non-snapshot graph nodes
  ignore-single: false
