#
# This is a template - not used at runtime
#
repos:
  # format: repo_url [ - internal_directory_where_the_dependency_tree_command_is_executed ]
  - https://github.com/org/repo-1
  - https://github.com/org/repo-2
  - https://github.com/org/repo-3 - repo/internal/dir

# local directory where the repositories are cloned
workDirectory: /home/user/tmp/dep-viz

gitConfig:
  executable: /usr/bin/git
  username: user
  token: abcdefabcdefabcdefabcdefabcdefabcdef

mavenConfig:
  executable: /usr/bin/mvn
  goal: dependency:tree
  scope: compile
  # root(s) of dependency sub-trees to be considered for processing
  includes: com.sonatype.*,org.sonatype.*
  # reg exp has to match the includes above
  dependencyTreePattern: '[-+ \\|]*(com|org)\.sonatype\..+'

graphvizConfig:
  executable: /usr/bin/dot
  format: svg
  output: dep-graph.svg

features:
  # set to 'true' if you want to skip rendering of single version, non-snapshot graph nodes
  ignore-single: false

