name: Sarif push

on:
  workflow_dispatch:

jobs:
  push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
    
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: test.sarif
