# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Sonatype IQ Policy Evaluation
      uses: sonatype-nexus-community/iq-github-action@master
      with:
        serverUrl: https://75df-2607-fea8-809e-cf30-353f-3a0b-3e5a-105f.ngrok-free.app
        username: ${{ secrets.IQ_USERNAME }}
        password: ${{ secrets.IQ_PASSWORD }}
        applicationId: local-iq-app
        stage: Build
        target: ./target/
        
