# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Build with Maven
      run: mvn -B package --file pom.xml
        
    - name: IQ Evaluate
      id: evaluate
      uses: sonatype/actions/evaluate@v1
      with:
        username: ${{ secrets.SSA_USERNAME }}
        password: ${{ secrets.SSA_PASSWORD }}
        iq-server-url: https://sonatype.sonatype.app/platform
        application-id: testdata
#        result-file: result
#        keep-scan-file: true
        scan-targets: '**/*.jar'
        debug: false
        ignore-system-errors: true
        ignore-scanning-errors: true
