# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Setup IQ CLI Action
      id: setup-iq-cli
      uses: sonatype/actions/setup-iq-cli@v1
      with:
        iq-cli-version: 'latest'
        
    - name: Run IQ CLI
      id: evaluate
      uses: sonatype/actions/run-iq-cli@v1
      with:
        username: ${{ secrets.SSA_USERNAME }}
        password: ${{ secrets.SSA_PASSWORD }}
        iq-server-url: https://sonatype.sonatype.app/platform
        application-id: testdata
#        result-file: result
#        keep-scan-file: true
        scan-targets: '**/*.jar'
        debug: false
        ignore-system-errors: true
        ignore-scanning-errors: true

    - name: Fetch SBOM
      uses: sonatype/actions/fetch-sbom@v1
      if: always() && steps.evaluate.outputs.scan-id
      with:
        scan-id: ${{ steps.evaluate.outputs.scan-id }}
        application-id: testdata
        iq-server-url: https://sonatype.sonatype.app/platform
        username: ${{ secrets.SSA_USERNAME }}
        password: ${{ secrets.SSA_PASSWORD }}
        sbom-standard: spdx
        sbom-version: 2.3
